#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App8.Resource", IsApplication=true)]

namespace App8
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AndroidHUD.Resource.Attribute.ahBarColor = global::App8.Resource.Attribute.ahBarColor;
			global::AndroidHUD.Resource.Attribute.ahBarLength = global::App8.Resource.Attribute.ahBarLength;
			global::AndroidHUD.Resource.Attribute.ahBarWidth = global::App8.Resource.Attribute.ahBarWidth;
			global::AndroidHUD.Resource.Attribute.ahCircleColor = global::App8.Resource.Attribute.ahCircleColor;
			global::AndroidHUD.Resource.Attribute.ahDelayMillis = global::App8.Resource.Attribute.ahDelayMillis;
			global::AndroidHUD.Resource.Attribute.ahRadius = global::App8.Resource.Attribute.ahRadius;
			global::AndroidHUD.Resource.Attribute.ahRimColor = global::App8.Resource.Attribute.ahRimColor;
			global::AndroidHUD.Resource.Attribute.ahRimWidth = global::App8.Resource.Attribute.ahRimWidth;
			global::AndroidHUD.Resource.Attribute.ahSpinSpeed = global::App8.Resource.Attribute.ahSpinSpeed;
			global::AndroidHUD.Resource.Attribute.ahText = global::App8.Resource.Attribute.ahText;
			global::AndroidHUD.Resource.Attribute.ahTextColor = global::App8.Resource.Attribute.ahTextColor;
			global::AndroidHUD.Resource.Attribute.ahTextSize = global::App8.Resource.Attribute.ahTextSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::App8.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::App8.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::App8.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::App8.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::App8.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::App8.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::App8.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::App8.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::App8.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::App8.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::App8.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::App8.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::App8.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarColor = global::App8.Resource.Styleable.ProgressWheel_ahBarColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarLength = global::App8.Resource.Styleable.ProgressWheel_ahBarLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarWidth = global::App8.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahCircleColor = global::App8.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahDelayMillis = global::App8.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRadius = global::App8.Resource.Styleable.ProgressWheel_ahRadius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimColor = global::App8.Resource.Styleable.ProgressWheel_ahRimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimWidth = global::App8.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::App8.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahText = global::App8.Resource.Styleable.ProgressWheel_ahText;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextColor = global::App8.Resource.Styleable.ProgressWheel_ahTextColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextSize = global::App8.Resource.Styleable.ProgressWheel_ahTextSize;
			global::Gcm.Client.Resource.String.library_name = global::App8.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010009
			public const int ahBarColor = 2130771977;
			
			// aapt resource value: 0x7f010011
			public const int ahBarLength = 2130771985;
			
			// aapt resource value: 0x7f010010
			public const int ahBarWidth = 2130771984;
			
			// aapt resource value: 0x7f01000e
			public const int ahCircleColor = 2130771982;
			
			// aapt resource value: 0x7f01000d
			public const int ahDelayMillis = 2130771981;
			
			// aapt resource value: 0x7f01000f
			public const int ahRadius = 2130771983;
			
			// aapt resource value: 0x7f01000a
			public const int ahRimColor = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int ahRimWidth = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int ahSpinSpeed = 2130771980;
			
			// aapt resource value: 0x7f010006
			public const int ahText = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int ahTextColor = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int ahTextSize = 2130771976;
			
			// aapt resource value: 0x7f010003
			public const int buttonSize = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int colorScheme = 2130771972;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			// aapt resource value: 0x7f010005
			public const int scopeUris = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040008
			public const int common_google_signin_btn_text_dark = 2130968584;
			
			// aapt resource value: 0x7f040000
			public const int common_google_signin_btn_text_dark_default = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int common_google_signin_btn_text_dark_disabled = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int common_google_signin_btn_text_dark_focused = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int common_google_signin_btn_text_dark_pressed = 2130968579;
			
			// aapt resource value: 0x7f040009
			public const int common_google_signin_btn_text_light = 2130968585;
			
			// aapt resource value: 0x7f040004
			public const int common_google_signin_btn_text_light_default = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int common_google_signin_btn_text_light_disabled = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int common_google_signin_btn_text_light_focused = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int common_google_signin_btn_text_light_pressed = 2130968583;
			
			// aapt resource value: 0x7f04000a
			public const int common_google_signin_btn_tint = 2130968586;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int butonikuq = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Cancelicon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_full_open_on_phone = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_google_signin_btn_icon_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_dark_focused = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_dark_normal = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_dark_normal_background = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_disabled = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_light = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_light_focused = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_icon_light_normal = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_icon_light_normal_background = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_text_dark = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_dark_focused = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_dark_normal = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_dark_normal_background = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_disabled = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_light = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_light_focused = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_light_normal = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_google_signin_btn_text_light_normal_background = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int edittext = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int googleg_disabled_color_18 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int googleg_standard_color_18 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int Helpicon = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_errorstatus = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_launcher = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_successstatus = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int Icon = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int icon1 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int Notification = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int Okicon = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int Perdorues = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int roundedbg = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int roundedbgdark = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int settingsicon = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int settingsicon1 = 2130837541;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080000
			public const int adjust_height = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int adjust_width = 2131230721;
			
			// aapt resource value: 0x7f080006
			public const int auto = 2131230726;
			
			// aapt resource value: 0x7f080019
			public const int button1 = 2131230745;
			
			// aapt resource value: 0x7f080029
			public const int buttonndrysho = 2131230761;
			
			// aapt resource value: 0x7f080007
			public const int dark = 2131230727;
			
			// aapt resource value: 0x7f080025
			public const int email = 2131230757;
			
			// aapt resource value: 0x7f080003
			public const int icon_only = 2131230723;
			
			// aapt resource value: 0x7f080026
			public const int imageButton1 = 2131230758;
			
			// aapt resource value: 0x7f080027
			public const int imageButton2 = 2131230759;
			
			// aapt resource value: 0x7f080028
			public const int imageButton3 = 2131230760;
			
			// aapt resource value: 0x7f080010
			public const int imageButtonpass = 2131230736;
			
			// aapt resource value: 0x7f080020
			public const int indeksi = 2131230752;
			
			// aapt resource value: 0x7f08001f
			public const int klasa = 2131230751;
			
			// aapt resource value: 0x7f080008
			public const int light = 2131230728;
			
			// aapt resource value: 0x7f080011
			public const int linearLayout1 = 2131230737;
			
			// aapt resource value: 0x7f080013
			public const int linearLayout2 = 2131230739;
			
			// aapt resource value: 0x7f08000f
			public const int linearLayout20 = 2131230735;
			
			// aapt resource value: 0x7f080015
			public const int linearLayout3 = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int linearLayout4 = 2131230742;
			
			// aapt resource value: 0x7f080018
			public const int linearLayout5 = 2131230744;
			
			// aapt resource value: 0x7f08001a
			public const int linearLayout6 = 2131230746;
			
			// aapt resource value: 0x7f08001c
			public const int listView1 = 2131230748;
			
			// aapt resource value: 0x7f08000d
			public const int loadingImage = 2131230733;
			
			// aapt resource value: 0x7f08000b
			public const int loadingProgressBar = 2131230731;
			
			// aapt resource value: 0x7f08000e
			public const int loadingProgressWheel = 2131230734;
			
			// aapt resource value: 0x7f080002
			public const int none = 2131230722;
			
			// aapt resource value: 0x7f080021
			public const int nxenesit = 2131230753;
			
			// aapt resource value: 0x7f080023
			public const int pass = 2131230755;
			
			// aapt resource value: 0x7f080017
			public const int pass_edit = 2131230743;
			
			// aapt resource value: 0x7f080022
			public const int perd_emri = 2131230754;
			
			// aapt resource value: 0x7f080014
			public const int perdoruesi_edit = 2131230740;
			
			// aapt resource value: 0x7f080024
			public const int perserit_pass = 2131230756;
			
			// aapt resource value: 0x7f08001d
			public const int qyteti = 2131230749;
			
			// aapt resource value: 0x7f08001e
			public const int shkolla = 2131230750;
			
			// aapt resource value: 0x7f080004
			public const int standard = 2131230724;
			
			// aapt resource value: 0x7f080009
			public const int textView1 = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int textView2 = 2131230730;
			
			// aapt resource value: 0x7f080012
			public const int textView3 = 2131230738;
			
			// aapt resource value: 0x7f08000c
			public const int textViewStatus = 2131230732;
			
			// aapt resource value: 0x7f08001b
			public const int textViewemri = 2131230747;
			
			// aapt resource value: 0x7f08002a
			public const int tv = 2131230762;
			
			// aapt resource value: 0x7f080005
			public const int wide = 2131230725;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int google_play_services_version = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int listviewlayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int loading = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int loadingimage = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int loadingprogress = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ndihme = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Notat = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Perdorues = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Rregullime = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int spinnerlayout = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int XMLFile1 = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050017
			public const int ApplicationName = 2131034135;
			
			// aapt resource value: 0x7f050016
			public const int Hello = 2131034134;
			
			// aapt resource value: 0x7f050011
			public const int app_name = 2131034129;
			
			// aapt resource value: 0x7f050000
			public const int common_google_play_services_enable_button = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int common_google_play_services_enable_text = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int common_google_play_services_enable_title = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int common_google_play_services_install_button = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int common_google_play_services_install_text = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int common_google_play_services_install_title = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int common_google_play_services_notification_ticker = 2131034118;
			
			// aapt resource value: 0x7f050010
			public const int common_google_play_services_unknown_issue = 2131034128;
			
			// aapt resource value: 0x7f050007
			public const int common_google_play_services_unsupported_text = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int common_google_play_services_update_button = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int common_google_play_services_update_text = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int common_google_play_services_update_title = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int common_google_play_services_updating_text = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int common_google_play_services_wear_update_text = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int common_open_on_phone = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int common_signin_button_text = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int common_signin_button_text_long = 2131034127;
			
			// aapt resource value: 0x7f050014
			public const int firebase_database_url = 2131034132;
			
			// aapt resource value: 0x7f050013
			public const int gcm_defaultSenderId = 2131034131;
			
			// aapt resource value: 0x7f050015
			public const int google_storage_bucket = 2131034133;
			
			// aapt resource value: 0x7f050012
			public const int library_name = 2131034130;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int button_text = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] ProgressWheel = new int[] {
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985};
			
			// aapt resource value: 3
			public const int ProgressWheel_ahBarColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_ahBarLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_ahBarWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_ahCircleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_ahDelayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_ahRadius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_ahRimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_ahRimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_ahSpinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_ahText = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_ahTextColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_ahTextSize = 2;
			
			public static int[] SignInButton = new int[] {
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
